version: "3"
services:

  auth-postgres:
    image: postgres:10-alpine
    container_name: auth-postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=auth_room214
      - POSTGRES_USER=auth_room214
      - POSTGRES_PASSWORD=auth_room214
    ports: 
      - "127.0.0.1:5432:5432"