# Generated by Django 2.2.7 on 2019-12-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='room',
            field=models.TextField(default='214', null=True),
        ),
    ]
